http:
  routers:
    code-server:
      rule: "Host(`controlia.shop`)"
      service: "service-code-server"
      entryPoints:
        - "websecure"
  services:
    service-code-server:
      loadBalancer:
        servers:
          - url: "http://code-server:8443"
  middlewares:
    strip-prefix:
      stripPrefix:
        prefixes:
          - "/"
